### ISSUE TITLE
Has graphite survey on branch submit sometimes

### ISSUE THREAD

**Issue by sareini** [bradymadden97/freephite#16]
<img width="804" alt="Screenshot 2023-08-18 at 2 50 43 PM" src="https://github.com/bradymadden97/freephite/assets/26151060/e14310ee-579b-45f7-b88b-bd6776f3144a">

ran a branch submit and saw this

**Comment by bradymadden97** [comment]
https://github.com/bradymadden97/freephite/pull/19 should address this
