### ISSUE TITLE
Graphite routes are being deprecated

### ISSUE THREAD

**Issue by guilhermevrs** [bradymadden97/freephite#18]
Hey there

We noticed that graphite is deprecating their `@withgraphite/graphite-cli-routes` package.

looking at the code, it seems `freephite` still uses it to get PR information when doing the sync (e.g. when running `fp repo sync`).

I think we can bypass that and use the GH api directly - this way we remove the Graphite API dep.

What do you think?

**Comment by guilhermevrs** [comment]
@bradymadden97 I took a stab at the problem - let me know what you think

**Comment by bradymadden97** [comment]
Hey @guilhermevrs, thank you for the contribution! I'll pull this down and test it tomorrow.

Are you all using freephite at datadog?

**Comment by guilhermevrs** [comment]
I wouldn't say all, no 😅 
Some folks use `git machete` or other alternatives. Some others don't do stacked PRs.

I had the same idea (keep all the nice git commands but replace graphite api by pure GH api) and I was glad to see you were already doing it.
So I spread the word :)
